name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Update to the latest checkout action version (v3)
      - name: Checkout Code
        uses: actions/checkout@v3

      # Update to the latest setup-node action version (v3)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Or use '20' if your project supports Node.js 20

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Use the updated version here too

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Or '20' based on project requirements

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
