name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: List directory contents
      run: ls -la

    - name: Check for package.json
      id: check_package
      run: |
        if [ -f "package.json" ]; then
          echo "package_exists=true" >> $GITHUB_OUTPUT
        else
          echo "package_exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Set up Node.js
      if: steps.check_package.outputs.package_exists == 'true'
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      if: steps.check_package.outputs.package_exists == 'true'
      run: npm ci

    - name: Run tests
      if: steps.check_package.outputs.package_exists == 'true'
      run: npm test

    - name: Build project
      if: steps.check_package.outputs.package_exists == 'true'
      run: npm run build

    - name: Run generic checks
      run: |
        echo "Running generic checks..."
        # Add any generic checks here, for example:
        # - Check for presence of important files
        # - Run linters if available
        # - Perform static code analysis

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v3

    - name: Deploy to production
      run: |
        echo "Add your deployment steps here"
        # For example:
        # - ssh into your server
        # - pull the latest changes
        # - restart your application
